name: PEPE Signals & Alerts

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  send_signals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Send Signals
        run: python send_signals.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:    ${{ secrets.TELEGRAM_CHAT_ID }}
          PEPE_ALERT_LEVEL:    ${{ secrets.PEPE_ALERT_LEVEL }}

  check_alerts:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Check Alerts
        run: python check_alerts.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:    ${{ secrets.TELEGRAM_CHAT_ID }}
