name: PEPE Signals & Alerts

on:
  schedule:
    - cron:  '*/30 * * * *'   # her 30 dakikada bir sinyal
    - cron:  '*/10 * * * *'   # her 10 dakikada bir uyarı

jobs:
  signals:
    if: github.event.schedule[0].cron == '*/30 * * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python send_signals.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ETHERSCAN_API_KEY:  ${{ secrets.ETHERSCAN_API_KEY }}

  alerts:
    if: github.event.schedule[1].cron == '*/10 * * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python check_alerts.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          PEPE_ALERT_LEVEL:   ${{ secrets.PEPE_ALERT_LEVEL }}
