name: PEPE Signals & Alerts

# 10 dakikada bir çalışsın
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  send_signals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install --no-cache-dir -r requirements.txt
      - run: python send_signals.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PEPE_ALERT_LEVEL: ${{ secrets.PEPE_ALERT_LEVEL }}

  check_alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install --no-cache-dir -r requirements.txt
      - run: python check_alerts.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
